version: "3.4"
services:
  web:
    image: dsanders14/tcmg412-api
    environment:
      - SLACK_URL
    ports:
      - "80:5000"
    networks:
      - webnet
  redis: 
    image: redis
    networks:
      - webnet
    ports:
      - "6379:6379"
networks:
  webnet:
