name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Test File
      run: |
        cd API-TEST
        docker build -t dsanders14/tcmg412-test-file .
      
    - name: Build API
      run: |
        cd api
        docker build -t dsanders14/tcmg412-api .
    
    - name: Docker compose
      run: |
        cd api
        docker-compose up -d
    
    - name: Docker ps
      run: docker ps
    
    - name: Test Code
      run: |
        cd api
        docker run dsanders14/tcmg412-test-file
    
    - name: Pushing image
      run: |
        docker login -u ${{ secrets.Dylan_username}} -p ${{ secrets.Dylan_password}}
        docker image tag dsanders14/tcmg412-docker dsanders14/tcmg412-docker:latest
        docker image tag dsanders14/tcmg412-docker dsanders14/tcmg412-docker:$(date +%s)
        docker image push --all-tags dsanders14/tcmg412-docker
